version: '3.7'

services:
  nest:
    container_name: 'nest'
    build:
      context: .
      target: builder
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - env/local.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_DATABASE=connectabil_test
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
networks:
  webnet:
volumes:
  mongodb_data_container:
